### ISSUE TITLE
de-DE translation

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/crouton#162]
"days_of_the_week": ["", "Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Frietag", "Samstag"],
			"weekday": '',
			"city": "",
			"cities": "",
			"groups": "",
			"areas": "",
			"locations": "",
			"counties": "",
			"states": "",
			"postal_codes": "",
			"formats": "",
			"map": ""

**Comment by radius314** [comment]
@otrok7 could help complete the above translation?

**Comment by otrok7** [comment]
"days_of_the_week": ["", "Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Frietag", "Samstag"],
		"weekday": 'Wochentag',
		"city": "Stadt",
		"cities": "Städte",
		"groups": "Gruppen",
		"areas": "Gebiete",
		"locations": "Orte",
		"counties": "Landkreise",
		"states": "Bundesländer",
		"postal_codes": "PLZ",
		"formats": "Formate",
		"map": "Karte"


I had to discuss "Counties" with a few people...Generally, in Germany there's no administrative entity between the city and the state, and in the case of Berlin and Hamburg, the city is the state.  But smaller towns could group together in a Landkreise...so that's sort of the closest.

**Comment by otrok7** [comment]
And of course, the list is a bit specific to Germany, only Germany has Bundesländer...the Swiss have Kantonen. and who know what the Austrians have.

**Comment by radius314** [comment]
released in crouton 3.4.3
