### ISSUE TITLE
how-to

### ISSUE THREAD

**Issue by abna-brasil** [bmlt-enabled/crouton#192]
Hello everybody

We are here from Brazil, starting a new BMLT server and we'd like to make some configuration to fit well our wp crouton interface.
first (of 12!) question
When we use shortcode distance_search="65" interface just show meetings under this range, but we'd like to just start in this range, but if user want's to navegate to all places, around the globe...

**Comment by radius314** [comment]
are you using wordpress?

**Comment by ChrisMarshallNY** [comment]
Howdy!
The others could answer more definitively, but the easiest way is to use TOMATO as your Root Server. This gives the client worldwide access.
However, especially with Crouton, you need to be careful, because Crouton caches a load of data, so you need to select shortcodes that prevent it from just going out and reading the entire server.

**Comment by abna-brasil** [comment]
Hi, I already did it...I seted tomato as root server... but stil not showing all meetings.May I need to remove distance_search="65"?
And yes, we are using wp...

**Comment by abna-brasil** [comment]
Hello,
I get it...
I just need to set tomato as root server and use the shortcode service_body_parent with our world service body ID
Tks a lot
