### ISSUE TITLE
3rd column is taking up too much real estate

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/crouton#231]
![image](https://user-images.githubusercontent.com/1850811/79015745-69690a80-7b3b-11ea-9c8f-b9493bb94bef.png)

**Comment by alanborning** [comment]
I noticed this as well, and would like to contribute a pull request to fix this. But first I wanted to get feedback on the solution. My preference is to change the `webLinkify` function in `crouton-core.js` to have a second optional parameter n, which if present is the maximum length string to be linkified. If the string is longer than n, display the first n-5 characters plus " ...." (the link itself in the href would remain unaltered of course).

An alternative, which I don't like quite as much, would be to either insert some zero-width spaces, or use `word-break: break-all` in some css. Long URLs, for example zoom links with a password, would still be really long but could spread over more lines. A final option is to just leave the code as is, and let people put “Video meeting link” in the template instead of the text of the URL (this doesn't require any code changes, maybe just documenting a hint).

**Comment by radius314** [comment]
If I understand correctly, this would mean that it would appear as if the link was summarized.  My worry here is that less technical folk would assume that the link is bad (not understanding how anchor `<a/>` tags work.  Thus resulting in UX issues and possible frustration.  I do like the ability to handle optionally, however most people do not modify the default templates from what I understand.  Seemingly you could do a similar textual truncation with custom CSS (`text-overflow: ellipsis;`).

With that said, you could possibly make the link a button and further simplify.  However I chose to go with the link because of a belief in an association with the URL that seems familiar, and also how folks might copy and paste links.

There could be a potential hybrid solution of using the ellipsis overflow and then possible some kind of hover over effect that shows the full url.

**Comment by radius314** [comment]
I'll do some prototyping tomorrow and post some screen shots of some ideas.  Please feel free to do the same.

**Comment by radius314** [comment]
didn't get to this today, hopefully will tomorrow.

**Comment by radius314** [comment]
I have a fix in to be beta-tested.

**Comment by radius314** [comment]
This has been resolved and released in crouton 3.11.2
