### ISSUE TITLE
Modify Helper Functions for Hybrid and In-Person

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/crouton#253]
Currently, the helper function for Hybrid meetings {{meetsHybrid}} adds the statement "A MEETING THAT MEETS IN-PERSON AND VIRTUALLY SIMULTANEOUSLY."   The helper functions for Virtual {{meetsVirtually}} adds just "MEETS VIRTUALLY" (and doesn't specify that it is "A MEETING THAT...". So my suggestion is to modify the helper to remove "A MEETING THAT" and leave only "MEETS IN-PERSON AND VIRTUALLY SIMULTANEOUSLY" 

I'm actually not sure if "simultaneously" is the best word either, because we know now that some groups coming out of the pandemic are hosting both an in-person and a virtual meeting but not a "Hybrid" meeting, rather they are being held as two separate meetings. So those are also held "simultaneously" only not together. I'm not sure of the better word to use but thought I would throw that out there.

Also, as long as I'm putting in the feature request... can we add a helper function for {{meetsInPerson}} that will add "MEETS IN-PERSON"? As long as we're specifying the "MEETS VIRTUALLY" and the "MEETS IN-PERSON AND VIRTUALLY SIMULTANEOUSLY", the crouton table cell looks empty with just a map link for the in-person only meetings.  Personally, I've chosen to use the `class='glyphicon glyphicon-user'` for that before the statement. But now we're getting into the Metadata Template so that can be for another time.

**Comment by radius314** [comment]
For the first part of the request, you are observing the default fallback
text.  If you want something different you can modify the "Description"
field for the format in the root server.  For meetsHybrid it's going to use
the description for HY.  It does not seem to make sense to me to change the
default text to something you specifically want until enough people lobby
for it.

The second part of your request seems reasonable to me, however the logic
is such that it uses a format to determine the description.  This is
particularly important behavior because of the fact that crouton supports
multiple languages.  The text you are seeing, as mentioned prior is the
fallback text (which is in English).  So if we were to implement this
behavior, we'd have to also associate with a format to give the ability to
customize the text.  Also given the changes in 3.11.0, we only return
formats for the dataset returned (this reduced the number of HTTPS requests
by one, improving performance of crouton).  So there would be no easy way
to get the text for this, unless you required the meetings actually were
tagged with the "IN PERSON" format.  This seems hardly like a good
workflow.  Since this is the first time this request is coming up and there
are viable workarounds, I would opt not to implement this feature right now.

That being said, I will leave the ticket open for folks to chime in, 👍🏻
it they feel strongly about it.

**Comment by tempsaint** [comment]
My apologies... I was misreading the code. And the formats... as I overlooked the "description" and was looking at the "Name".  Ugh. 

As for the second part - I need for a matching format was mentioned in another conversation and I think I forgot it. I was able to add "MEETS IN-PERSON" to the metadata template easy enough. This part of the request was added just because i was requesting the hybrid modification. I wasn't going to submit this alone. 

My apologies for an apparent waste of bandwidth.
