### ISSUE TITLE
Have an EDIT button in crouton

### ISSUE THREAD

**Issue by paulnagle** [bmlt-enabled/crouton#274]
This might be a path towards modernising the BMT Administrator interface

**Describe the solution you'd like**
Similar to how Contact details are displayed in Crouton when an Administrator is signed in to BMLT, we should also have an EDIT button to allow changes to be made to any individual meeting.

The meeting details as displayed in Crouton would be changed to an editable form when the EDIT button is clicked. The EDIT button would change to a SAVE button, and when the details of the meeting were amended and the SAVE button clicked, the updates to the meeting would be pushed to the DB.

I realise that this would be a lot of work but it may be a good option for a modernised BMLT Administration interface.

**Comment by radius314** [comment]
I am going to take a first pass at an MVP of this.  It will be a simple button that opens a modal and allows some to suggest changes.  The resulting effect will be an email sent to a pre-defined address that will share those changes.  

Obviously there are a lot of other things that would have to be added to truly support this feature.  The intention here would be to shift meeting updates further left.

I don't see this as a replacement for modernizing the BMLT interface but rather a way to deal with the major fluctuations in change meetings in the world today.  

Future work could include a submittal API to the root server that queues up these changes.

**Comment by brustar64** [comment]
I'd like to upvote this enhancement :)

**Comment by tempsaint** [comment]
I think if a site is running both crouton and bmlt-workflow it would be cool to have an Edit button display that would bring up a model of the bmlt-workflow. If that's too advanced, maybe just have an Edit button that takes the user to the bmlt-workflow form with the details of the meeting pre-selected. I recently asked/mentioned this in the bmlt-workflow channel on slack.

**Comment by otrok7** [comment]
I'm not sure how bmlt-workflow works, but this might be something you can already do with the templates.  For instance, in Germany, I have a link on the meeting-details page, under "contacts", that either opens a "mailto:" or a contact form.  For the mailto, it gets the service body's E-Mail address from BMLT, and generates a subject line from the meeting data.  If opening bmlt-workflow can be done with a link, I can support you on implementing this locally.

**Comment by dgershman** [comment]
The easiest thing to do would be to deep link to bmlt workflow for that meeting if it’s possible.  I would make that a strict requirement of this feature.  The mail to feature you are describing will result in a lot of support questions due to the way each persons system could be configured and ultimately would not achieve the desired outcome.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by otrok7** [comment]
I'm not sure what you mean by "strict requirement".  Do you mean you think that this is something that should be a very hight priority to be implemented?  Or that there should be strict requirements regarding its use?  I wasn't really proposing my mail solution as a general way, because we can never be sure if the service body email should be public, otherwise this would already be part of crouton.

**Comment by dgershman** [comment]
This feature is kind of dead because of BMLT workflow
