### ISSUE TITLE
No Meetings Found - False Flag

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/crouton#460]
**Describe the bug**
we are displaying service body "35" on https://www.na.org.au/multi/na-online-australia/
It displays the meetings but also produces and error warning

![image](https://github.com/bmlt-enabled/crouton/assets/29008815/0d48bae6-7091-462e-ba58-8cdfaf8f50c6)

**To Reproduce**
Go to https://www.na.org.au/multi/na-online-australia/

**Expected behavior**

**Screenshots**
As above

**Desktop (please complete the following information):**
all platforms all browsers

**Smartphone (please complete the following information):**
All handsets 

**Additional context**
the shortcode is - [bmlt_tabs service_body="35"]

**Comment by brustar64** [comment]
same code works on https://brucegardner.net/myworld/test-page/

**Comment by otrok7** [comment]
Hi Bruce, the problem here is that since embedded maps are now on by default, the code is trying to generate a map for a bunch of virtual meetings.  I'm going to modify the code so that the map will be turned off in this case.  But until the fix is released, you can just set "show_map=0" in your shortcode.

**Comment by brustar64** [comment]
Thank you so much! :)

**Comment by otrok7** [comment]
fixed in 3.18.4
