### ISSUE TITLE
QR Codes no longer displaying 

### ISSUE THREAD

**Issue by kaldoon** [bmlt-enabled/crouton#473]
**Describe the bug**
QR Code has stopped displaying underneath meeting link - virtual-na.org and the new share button is not visible in firefox - chrome and edge the share button is there

**To Reproduce**
1. Go to Meeting Tab  - display
2. See error

**Expected behavior**
have qr code display as it did

**Screenshots**
![firefox04082024](https://github.com/bmlt-enabled/crouton/assets/91600452/7c77ff0b-bb40-4482-9dc5-a8a1a0692795)
![Screenshot 2024-04-08 090325](https://github.com/bmlt-enabled/crouton/assets/91600452/15309d31-5a44-4150-bdf2-4d8321f14865)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by otrok7** [comment]
Crouton relies on the browser to generate a "share".  It's not surprising that not all browsers on all devices support the "share" button.

QRCodes rely on an external service to generate the image.  Up to now, we used chart.googleapis.com, but this has since been deprecated.  I moved to another service.

**Comment by otrok7** [comment]
Please test against 3.18.10.

**Comment by kaldoon** [comment]
updated 3.18.10 - tested no change

**Comment by kaldoon** [comment]
working now - you are probably correct - thank you for your service
